name = "BartIO"
uuid = "8b90e6a2-6e4d-4906-89ae-b5f72ca4a65b"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>",
            "Aurélien Trotier <a.trotier@gmail.com>"]
version = "0.2"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
