name = "BartIO"
uuid = "8b90e6a2-6e4d-4906-89ae-b5f72ca4a65b"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>",
            "Aurélien Trotier <a.trotier@gmail.com>"]

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
